# This is a basic workflow to help you get started with Actions

name: Update JWT on Mock Server

# Controls when the workflow will run
on:
  schedule:
  - cron: "3 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Update JWT
        uses: pietroid/jwt-server-updater-action@v1.0
        with:
          twilioAccountSid: ${{ secrets.twilioAccountSid }}
          twilioApiKey: ${{ secrets.twilioApiKey }}
          twilioApiSecret: ${{ secrets.twilioApiSecret }}
          serviceSid: ${{ secrets.serviceSid }}
          mockServerURL: ${{ secrets.mockServerURL }}
          postmanEnvURL: ${{ secrets.postmanEnvURL }}
          mockServerEnvID: ${{ secrets.mockServerEnvID }}
          postmanAPIKey: ${{ secrets.postmanAPIKey }}
          
